# Generated by Django 4.2 on 2024-03-15 12:21

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=100)),
                ("last_name", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(default="", max_length=100)),
                ("phone_number", models.CharField(default="", max_length=20)),
                ("reservation_date", models.DateField(default=datetime.date.today)),
                ("reservation_time", models.TimeField()),
                ("party_size", models.PositiveIntegerField(default=2)),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        default="Thankyou for asking!!, No special request for now",
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                ("updated_at", models.TimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("checkedout", "Checkedout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bookingId",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed_date", models.DateField(auto_now=True)),
                ("rating", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(max_length=800)),
                (
                    "bookingId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="details.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "menu_item_description",
                    models.TextField(
                        default="No description available", max_length=1000
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_special", models.BooleanField(default=True)),
                ("is_recommended", models.BooleanField(default=True)),
                (
                    "calories",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fat_content",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("allergens", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="details.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu_images/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateField(auto_now=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="details.menu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.FileField(
                        null=True,
                        upload_to="feedimage/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="details.feedback",
                    ),
                ),
            ],
        ),
    ]
